name: pipeline

permissions:
  contents: write

# This workflow triggers on each push to the main branch
on:
  push:
    branches:
      - feature/*
      - main
      

jobs:
  basic-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.email "huiyang.wang621@gmail.com"
          git config --global user.name "Anne Pipeline"

      - name: Loop through each month and upload data
        run: |
          cd script/data
          mkdir BTC_USDT
          cd BTC_USDT
          echo "demo" > demo.txt
          # Define start year and current year
          START_YEAR=2021
          CURRENT_YEAR=$(date +"%Y")

          # Loop through each year from 2021 to the current year
          for year in $(seq $START_YEAR $CURRENT_YEAR); do
            # Loop through each month (01 to 12)
            for month in $(seq -w 1 12); do
              identifier="${year}${month}"
              url="https://download.gatedata.org/spot/candlesticks_1d/${identifier}/BTC_USDT-${identifier}.csv.gz"
              gz_file="BTC_USDT-${identifier}.csv.gz"
              csv_file="BTC_USDT-${identifier}.csv"

              # Download .gz file and process it
              curl -O $url
              if [[ -f "$gz_file" ]]; then
                zcat "$gz_file" > "$csv_file"
                rm -rf "$gz_file"
                git add "$csv_file"
                git commit -m "Upload data for ${identifier}"
                git push origin main
              fi
            done
          done
          
#          # Combine all BTC*.csv files into one single file without duplicate headers
#          awk 'FNR==1 && NR!=1 {next} {print}' script/data/BTC*.csv > script/data/combined_BTC_USDT.csv
#
#          git add "$csv_file"
#          ls -ll
#          git commit -m "Combined all BTC CSV files into one"
#          git push origin main

