name: pipeline
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - main

jobs:

  basic-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run bash script
        run: |
          wc -l script/output/VMT_USDT-202408.csv
          pwd
          ls -ll
          curl -O https://download.gatedata.org/spot/candlesticks_1d/202409/BTC_USDT-2024092812.csv.gz
          ls -ll
          mv *.gz script/data
          ls -ll
          ls -ll script/data
#          chmod +x script.sh  # Make sure the script is executable
#          ./script.sh
#          cd /home/runner/work/coin/coin/script/data
#          gunzip BTC_USDT-2024092812.csv.gz

#          python convert_timestamp.py
