name: pipeline

permissions:
  contents: write

# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - main

jobs:

  basic-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run bash script
        run: |
          git config --global user.email "huiyang.wang621@gmail.com"
          git config --global user.name "Anne Pipeline"
          wc -l script/output/VMT_USDT-202408.csv
          cd script/data
          curl -O https://download.gatedata.org/spot/candlesticks_1d/202408/BTC_USDT-202408.csv.gz
          zcat  BTC_USDT-202408.csv.gz > BTC_USDT-202408.csv
          rm *.gz
          ls -ll
          wc -l BTC_USDT-202408.csv
          git add *
          git commit -m "Upload data"
          git push
#          ls -ll script/data
#          chmod +x script.sh  # Make sure the script is executable
#          ./script.sh
#          cd /home/runner/work/coin/coin/script/data
#          gunzip BTC_USDT-2024092812.csv.gz

#          python convert_timestamp.py
